AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  BricklinkerPy

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  BricklinkTelegramFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: bricklink_telegram_bot/
      Handler: app.lambda_handler
      Runtime: python3.10
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: BUFFERED

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  BricklinkTelegramFunction:
    Description: "Bricklink Telegram Lambda Function ARN"
    Value: !GetAtt BricklinkTelegramFunction.Arn
  BricklinkTelegramFunctionIamRole:
    Description: "Implicit IAM Role created for BricklinkTelegramFunction"
    Value: !GetAtt BricklinkTelegramFunctionRole.Arn
  BricklinkTelegramFunctionEndpoint:
    Description: "BricklinkTelegramFunction URL Endpoint"
    Value:
      Fn::GetAtt: BricklinkTelegramFunctionUrl.FunctionUrl
